name: 'Copilot/Codex Auto Review Loop'
description: 'Automatically orchestrate a review loop between GitHub Copilot and Codex for pull requests'
author: 'dhabibi'

branding:
  icon: 'refresh-cw'
  color: 'blue'

inputs:
  pr_number:
    description: 'Pull request number to review'
    required: true
  repository:
    description: 'Repository in owner/repo format'
    required: false
    default: ${{ github.repository }}
  poll_interval:
    description: 'Time in seconds between polling for responses'
    required: false
    default: '30'
  timeout_seconds:
    description: 'Maximum time in seconds to wait for responses'
    required: false
    default: '3600'
  github_token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup GitHub CLI
      shell: bash
      run: |
        # Verify gh CLI is available
        gh --version

    - name: Checkout action repository
      uses: actions/checkout@v4
      with:
        repository: dhabibi/copilot-ralph-wiggum
        path: .copilot-ralph-wiggum
        sparse-checkout: |
          scripts/review-loop.sh

    - name: Setup review-loop script
      shell: bash
      run: |
        # Copy the script to a known location and make it executable
        cp .copilot-ralph-wiggum/scripts/review-loop.sh ./review-loop.sh
        chmod +x ./review-loop.sh

    - name: Run Auto-Review Loop
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        ./review-loop.sh \
          "${{ inputs.pr_number }}" \
          "${{ inputs.repository }}" \
          "${{ inputs.poll_interval }}" \
          "${{ inputs.timeout_seconds }}"
